# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('spinners', '0002_userspinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('user_spinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinners.UserSpinner')),
            ],
        ),
    ]
