# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spinners', '0003_spin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spin',
            name='user_spinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='spinners.UserSpinner'),
        ),
        migrations.AlterField(
            model_name='userspinner',
            name='spinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spinners', to='spinners.Spinner'),
        ),
    ]
