# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spinners', '0004_auto_20170720_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspinner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spinners', to=settings.AUTH_USER_MODEL),
        ),
    ]
